-- require('cscseccot.core.keymaps')
-- require('cscseccot.core.options')
require('cscseccot.core.color')
-- vim.cmd("autocmd Colorscheme * highlight NvimTreeNormal guibg=NONE")
-- vim.cmd("autocmd Colorscheme * highlight NvimTreeNormal guibg=NONE")
